# Edix Configuration File
# This file contains configuration settings for the Edix application

# Database settings
database:
  path: "/data/edix.db"
  auto_migrate: true
  backup_enabled: true
  backup_interval: "1h"

# Server settings
server:
  host: "0.0.0.0"
  port: 8000
  reload: false
  log_level: "info"
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3003"
    - "https://yourdomain.com"

# Security settings
security:
  secret_key: "your-secret-key-change-this-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Frontend settings
frontend:
  build_path: "edix/static"
  dev_port: 3003

# Features
features:
  websocket_enabled: true
  file_uploads: true
  export_formats: ["json", "csv", "xlsx"]
  max_file_size: "10MB"

# Logging
logging:
  level: "info"
  file: "/data/edix.log"
  rotation: "daily"
  retention: "30 days"
